DROP DATABASE IF EXISTS Extra1;
CREATE DATABASE Extra1;
USE Extra1;
CREATE TABLE Trainee(
	Account_ID				TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Full_Name				VARCHAR(50) NOT NULL UNIQUE KEY,
    Birth_Date				DATETIME DEFAULT NOW(),
    Gender					ENUM('male','female','unknow') NOT NULL UNIQUE KEY,
    ET_IQ					TINYINT UNSIGNED CHECK(ET_IQ <= 20),
    ET_Gmath				TINYINT UNSIGNED CHECK(ET_Gmath <= 20),
    ET_English				TINYINT UNSIGNED CHECK(ET_English <= 20),
   Training_Class			VARCHAR(50) NOT NULL,
   Evaluation_Notes			VARCHAR(500) NOT NULL
);
ALTER TABLE Trainee ADD COLUMN VTI_Account TINYINT UNSIGNED UNIQUE NOT NULL;

CREATE TABLE DataTypes1(
ID							INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,	
Name						VARCHAR(50) NOT NULL,
Code						CHAR(5) UNIQUE NOT NULL,
Modified_Date				TIMESTAMP DEFAULT NOW()
);
CREATE TABLE DataTypes2(  
ID							INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,	
Name						VARCHAR(50) NOT NULL,
Birth_Date					DATETIME DEFAULT NOW(),
Gender						ENUM('0','1'),
Is_Deleted_Flag				BIT NOT NULL
);
